[tool.poetry]
name = "poetry add pyopengl pyqt5 tensorflow"
version = "0.1.0"
description = ""
authors = ["g0c0de0rd1e <kqlykjk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
